name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        uses: nuxt/actions-yarn@master
        with:
          args: install

      - name: test
        uses: nuxt/actions-yarn@master
        with:
          args: test --ci --runInBand --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: 'reports/junit'
          JEST_JUNIT_OUTPUT_NAME: 'js-test-results.xml'

      - name: build
        uses: nuxt/actions-yarn@master
        with:
          args: build
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
